[package]
name = "aoc2021rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.3"
lazy_static = "1.4.0"
num = "0.4.0"
priority-queue = "1.3.0"
regex = "1.7.0"
